vich_uploader:
    db_driver: orm

    mappings:
        article:
            uri_prefix: /uploads
            upload_destination: "%kernel.project_dir%/public/uploads"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        bandMember:
            uri_prefix: /uploads/bandMembers
            upload_destination: "%kernel.project_dir%/public/uploads/bandMembers"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
