services:
    php:
        image: basaalt_server
        container_name: basaalt-php
        restart: always
        networks:
            - basaalt
            - webgateway
        build:
            context: .
            dockerfile: DockerFile
        labels:
            - traefik.enable=true
            - traefik.http.routers.basaalt.rule=Host(`basaalt.ju2breizh.fr`)
        depends_on:
            db:
                condition: service_healthy
                restart: true
    db:
        container_name: basaalt_database
        image: mysql
        restart: always
        volumes:
            - mysql_basaalt_data:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: basaalt
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        healthcheck:
            test: ["CMD-SHELL", "mysql -u root -proot -e 'SELECT 1'"]
            interval: 10s
            retries: 5
            start_period: 10s
            timeout: 10s
        networks:
            - basaalt
    # mailhog:
    #     image: mailhog/mailhog
    #     container_name: hr-mailhog
    #     ports:
    #         - "1025:1025"
    #         - "8025:8025"
    #     environment:
    #         MH_STORAGE: memory
    #     networks:
    #         - basaalt

volumes:
    mysql_basaalt_data:
        driver: local

networks:
    basaalt:
        driver: bridge
    webgateway:
        external: true
