services:
    php:
        image: basaalt_server
        container_name: basaalt-php
        restart: always
        networks:
            - webgateway
            - basaalt
        build:
            context: .
            dockerfile: DockerFile
        labels:
            - traefik.enable=true
            - traefik.http.routers.basaalt-php.rule=Host(`basaalt.ju2breizh.fr`)
        depends_on:
            db:
                condition: service_healthy
                restart: true
        ports: 
            - 80   
    db:
        container_name: basaalt_database
        image: mysql
        restart: always
        volumes:
            - mysql_basaalt_data:/var/lib/mysql:rw
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: basaalt
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        healthcheck:
            test: ["CMD-SHELL", "mysql -u root -proot -e 'SELECT 1'"]
            interval: 10s
            retries: 5
            start_period: 120s
            timeout: 10s
        networks:
            - basaalt
        ports:
            - 3306
volumes:
    mysql_basaalt_data:
        driver: local

networks:
    basaalt:
        driver: bridge
    webgateway:
        external: true
