name: test

on:
    workflow_call:
    push:
        branches-ignore:
            - main
    pull_request:
        branches-ignore:
            - main

jobs:
    unit-tests:
        name: Unit Tests
        runs-on: ubuntu-latest
        uses: actions/checkout@v3
        steps:
            - name: run unit tests
              run: make test
